In [ ]:
#一致性检验

In [1]:
import numpy as np
#numpy创造数组
A=np.array([[1,2,3,5,],[1/2,1,1/2,2],[1/3,2,1,1/2],[1/5,1/2,1/2,1]])
A

array([[1.        , 2.        , 3.        , 5.        ],
       [0.5       , 1.        , 0.5       , 2.        ],
       [0.33333333, 2.        , 1.        , 0.5       ],
       [0.2       , 0.5       , 0.5       , 1.        ]])

In [2]:
#获取A的行，shape获取形状信息
n=A.shape[0]
n

4

In [3]:
#eig_val特征值,eig_vec特征向量
eig_val,eig_vec=np.linalg.eig(A)
eig_vec

array([[ 0.86405421+0.j        , -0.95182159+0.j        ,
        -0.79805337+0.j        , -0.79805337-0.j        ],
       [ 0.32246053+0.j        ,  0.18049598+0.j        ,
         0.16709766+0.30294012j,  0.16709766-0.30294012j],
       [ 0.34608173+0.j        , -0.15419782+0.j        ,
         0.26085167-0.41413812j,  0.26085167+0.41413812j],
       [ 0.17221201+0.j        ,  0.19411309+0.j        ,
        -0.06121968+0.01070759j, -0.06121968-0.01070759j]])

In [4]:
Max_eig=max(eig_val)#求特征值最大值
Max_eig

np.complex128(3.9445215895321732+0j)

In [5]:
CI=(Max_eig- n)/(n-1)
RI=[0,0.00001,0.52,0.89,1.12,1.26,1.36,1.41,1.46,1.49,1.52,1.54,1.56,1.58,1.59,1.5943,1.6064,1.6133,1.6207,1.6292,1.6385,1.6403,1.6462,1.6497,1.6556,1.6587,1.6631,1.667,1.6693,1.6724]#百度对RI查表得，数值为1-30阶数矩阵的RI值
#则此处RI最多接受n=30
#ps,此处n=2一定为一致矩阵，CI=0，为了防止分母为0，将RI中第二个0，调整为0.00001
CR=CI/RI[n-1]
print('一致性指标CI=',CI)
print('一致性比例CR=',CR)
if CR<0.1:
    print('因为CR<0.10，所以该判断矩阵A的一致性可以接受')
else:
    print('注意：CR>=0.10,因此该判断矩阵A需要进行修改')

一致性指标CI= (-0.018492803489275584+0j)
一致性比例CR= (-0.0207784308868265+0j)
因为CR<0.10，所以该判断矩阵A的一致性可以接受


In [6]:
#算术平均法求权重

In [7]:
import numpy as np
A=np.array([[1,2,3,5,],[1/2,1,1/2,2],[1/3,2,1,1/2],[1/5,1/2,1/2,1]])
#可以通过指定axis参数来计算多维数组的某个维度上的元素总和。例如，在二维数组中，axis=0表示按列计算总和,axis=1表示按行计算总和
ASum=np.sum(A,axis=0)
#获取A的行和列
n=A.shape[0]
#归一化，二维数组除以一维数组扩展为与二维数组相同的形状，然后进行逐元素的除法运算
Stand_A=A/ASum
#各列相加到同一行
ASumr=np.sum(Stand_A,axis=1)
#计算权重向量
weights=ASumr/n
print(weights)

[0.51091873 0.19075348 0.19659858 0.1017292 ]


In [8]:
#几何平均法求权重

In [9]:
import numpy as np
A=np.array([[1,2,3,5,],[1/2,1,1/2,2],[1/3,2,1,1/2],[1/5,1/2,1/2,1]])
n=A.shape[0]
#np.power计算一维数组中所有元素的乘积
#可以通过指定axis参数来计算多维数组的某个维度上的元素总和。例如，在二维数组中，axis=0表示按列计算总和,axis=1表示按行计算总和
prod_A=np.prod(A,axis=1)
#np.power,对数组中的元素进行幂运算
#np.power(a,b),对数组中a的每个元素都按照b指数进行运算
prod_n_A=np.power(prod_A,1/n)
#归一化处理
re_prod_A=prod_n_A/np.sum(prod_n_A)
#展示权重结果
print(re_prod_A)



[0.53021607 0.19050881 0.17214414 0.10713098]


In [10]:
#特征值法求权重

In [11]:
import numpy as np
A=np.array([[1,2,3,5,],[1/2,1,1/2,2],[1/3,2,1,1/2],[1/5,1/2,1/2,1]])
n=A.shape[0]
eig_values,eig_vectors=np.linalg.eig(A)
#求最大特征值的索引，np.argmax,返回数组中最大值的索引
max_index=np.argmax(eig_values)
#找出对应的特征向量
max_vector=eig_vectors[:,max_index]
#对特征向量进行归一化处理，得到权重
weights=max_vector/np.sum(max_vector)
#输出权重
print(weights)

[0.5068336 +0.j 0.18914766+0.j 0.20300329+0.j 0.10101546+0.j]
